### ISSUE TITLE
styled_width_of on cell/text.rb should use with_font, shouldn't it?

### ISSUE THREAD

**Issue by commondream** [prawnpdf/prawn-table#42]
I was running into some column width sizing issues, and it looks like styled_width_of ends up using the font size for the current font on the pdf, not necessarily the font being used within the cell. Am I seeing that correctly?

**Comment by jessedoyle** [comment]
Hi everyone, I'm going to bump this issue because I just encountered it as well.

I just double-checked with `pry` and `styled_width_of` definitely appears use the document's base font size _and_ the document's base font.

I believe the cell's font and size should be used if specified.

Furthermore, it looks like the `M` character is naively used as a font's widest character ([link](https://github.com/prawnpdf/prawn-table/blob/master/lib/prawn/table/cell/text.rb#L136-L150)). This won't work well for icon fonts or any fonts with unusual character glyphs.

**Comment by jessedoyle** [comment]
Fix merged to master in 810ccdadc2486d6cba96b77e0fbb3a8731eb4732.

In the future, we should also look at calculating a font's widest character for `styled_width_of_single_character` instead of using the `M` character.
